-- AlterTable
ALTER TABLE "Tool" ADD COLUMN "description" TEXT,
ADD COLUMN "avgRating" DOUBLE PRECISION,
ADD COLUMN "upvoteCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "reviewCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "isTrending" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "verified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "launchDate" TIMESTAMP(3),
ADD COLUMN "useCases" TEXT,
ADD COLUMN "categories" JSONB,
ADD COLUMN "tags" JSONB,
ADD COLUMN "ttasks" JSONB;
